name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (si nécessaire)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  #

    - name: Build (si nécessaire)
      run: |
        # Si tu as un processus de build (par exemple avec un bundler), tu peux l'ajouter ici
        # Exemple : npm install && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  
